services:
  mysql:
    image: mysql:8.0
    container_name: lms-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: lms_pass
    volumes:
      - lms_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  lms_mysql_data:
